modLoader="javafml"
loaderVersion="[32,)"
license="BSD (3 clause)"

[[mods]]
modId="elementsofpower"
version="${file.jarVersion}"
displayName="Elements of Power"
updateJSONURL="https://raw.githubusercontent.com/gigaherz/ElementsOfPower/master/update.json"
issueTrackerURL="https://github.com/gigaherz/ElementsOfPower/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/elements-of-power"
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"
description='''
A magic mod about the raw power elemental essences
'''

[[dependencies.elementsofpower]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.108,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elementsofpower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="BOTH"
